# ─── Firmware principal T-Beam (capteur autonome complet) ────────────────────
[env:tbeam_main]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = hwgrep://CH9102
monitor_port = hwgrep://CH9102

lib_deps =
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    mikalhart/TinyGPSPlus @ ^1.0.3
    jgromes/RadioLib
    https://github.com/lewisxhe/XPowersLib.git


# ─── LoRa T-Beam V1.2 (SX1276) — Émetteur TEST ───────────────────────────────
[env:lora_tbeam_sender_test]
platform = espressif32@6.4.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = hwgrep://CH9102
monitor_port = hwgrep://CH9102
build_src_filter = -<*> +<../tests/lora_tbeam_sender/>

lib_deps =
    jgromes/RadioLib
    https://github.com/lewisxhe/XPowersLib.git
    mikalhart/TinyGPSPlus

# ─── LoRa Heltec WiFi LoRa 32 V3 (SX1262) — Récepteur TEST ──────────────────
[env:lora_heltec_receiver_test]
platform = espressif32@6.5.0
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_port = hwgrep://CP210x
monitor_port = hwgrep://CP210x
build_src_filter = -<*> +<../tests/lora_heltec_receiver/>

lib_deps =
    jgromes/RadioLib